# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"2\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\ninput_json\x18\x02 \x01(\t\"R\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"5\n\x0c\x42\x61tchRequest\x12%\n\x05tasks\x18\x01 \x03(\x0b\x32\x16.inference.TaskRequest\"7\n\rBatchResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.inference.TaskResult\"B\n\x0c\x43onfigUpdate\x12\x14\n\x0c\x66\x61ilure_rate\x18\x01 \x01(\x02\x12\x1c\n\x14inference_latency_ms\x18\x02 \x01(\x02\"\x17\n\tConfigAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x91\x01\n\rWorkerService\x12\x41\n\x0cProcessBatch\x12\x17.inference.BatchRequest\x1a\x18.inference.BatchResponse\x12=\n\x0cUpdateConfig\x12\x17.inference.ConfigUpdate\x1a\x14.inference.ConfigAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=80
  _globals['_TASKRESULT']._serialized_start=82
  _globals['_TASKRESULT']._serialized_end=164
  _globals['_BATCHREQUEST']._serialized_start=166
  _globals['_BATCHREQUEST']._serialized_end=219
  _globals['_BATCHRESPONSE']._serialized_start=221
  _globals['_BATCHRESPONSE']._serialized_end=276
  _globals['_CONFIGUPDATE']._serialized_start=278
  _globals['_CONFIGUPDATE']._serialized_end=344
  _globals['_CONFIGACK']._serialized_start=346
  _globals['_CONFIGACK']._serialized_end=369
  _globals['_WORKERSERVICE']._serialized_start=372
  _globals['_WORKERSERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
